services:
    postgres:
      image: postgres:17
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: shop
      healthcheck:
        test:
          ['CMD', 'pg_isready', '-U', "postgres", '-d', "shop"]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: unless-stopped
