FROM node:24-alpine AS builder

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

# ----
FROM node:24-alpine

WORKDIR /app

ENV DISABLE_MEDUSA_ADMIN=true
ENV MEDUSA_WORKER_MODE=worker
ENV PORT=9000

COPY --from=builder /app/.medusa/server /app/

ENV NODE_ENV=production

RUN npm install

EXPOSE 9000

CMD ["npm", "run", "start"]